return {
  lsp_servers = {
    { name = "pyright", package = "pyright" },
    { name = "ruff", package = "ruff" },
    { name = "ts_ls", package = "typescript-language-server" },
    { name = "lua_ls", package = "lua-language-server" },
    { name = "html", package = "html-lsp" },
    { name = "cssls", package = "css-lsp" },
    { name = "jsonls", package = "json-lsp" },
    { name = "yamlls", package = "yaml-language-server" },
    { name = "bashls", package = "bash-language-server" },
    { name = "dockerls", package = "dockerfile-language-server" },
    { name = "marksman", package = "marksman" },
  },
  formatters = {
    { name = "ruff_format", package = "ruff", executable = "ruff" },
    { name = "prettierd", package = "prettierd", executable = "prettierd" },
    { name = "stylua", package = "stylua", executable = "stylua" },
    { name = "shfmt", package = "shfmt", executable = "shfmt" },
  },
  formatters_by_ft = {
    python = { "ruff_format" },
    javascript = { "prettierd" },
    typescript = { "prettierd" },
    javascriptreact = { "prettierd" },
    typescriptreact = { "prettierd" },
    html = { "prettierd" },
    css = { "prettierd" },
    json = { "prettierd" },
    yaml = { "prettierd" },
    markdown = { "prettierd" },
    lua = { "stylua" },
    sh = { "shfmt" },
    bash = { "shfmt" },
  },
}
