return {
  lsp_servers = {
    { name = "ty", package = "ty" },
    { name = "ruff", package = "ruff" },
    { name = "ts_ls", package = "typescript-language-server" },
    { name = "lua_ls", package = "lua-language-server" },
    { name = "html", package = "html-lsp" },
    { name = "cssls", package = "css-lsp" },
    { name = "jsonls", package = "json-lsp" },
    { name = "yamlls", package = "yaml-language-server" },
    { name = "bashls", package = "bash-language-server" },
    { name = "dockerls", package = "dockerfile-language-server" },
    { name = "marksman", package = "marksman" },
  },
  formatters = {
    { name = "ruff_format", package = "ruff", executable = "ruff" },
    { name = "stylua", package = "stylua", executable = "stylua" },
    { name = "shfmt", package = "shfmt", executable = "shfmt" },
    { name = "oxfmt", package = "oxfmt", executable = "oxfmt" },
  },
  formatters_by_ft = {
    python = { "ruff_format" },
    lua = { "stylua" },
    sh = { "shfmt" },
    bash = { "shfmt" },
    javascript = { "oxfmt" },
    javascriptreact = { "oxfmt" },
    typescript = { "oxfmt" },
    typescriptreact = { "oxfmt" },
    json = { "oxfmt" },
    jsonc = { "oxfmt" },
    yaml = { "oxfmt" },
    markdown = { "oxfmt" },
  },
}
